---
- name: Copy zipped artifact to server
  copy:
    src: artifact.tar.gz
    dest: /tmp/artifact.tar.gz
    owner: ubuntu
    group: ubuntu
    mode: 0755

- name: Create directory for extraction
  file:
    path: /home/ubuntu/backend
    owner: ubuntu
    group: ubuntu
    mode: 0755
    state: directory

- name: Extract zipped artifact for backend
  unarchive:
    src: /tmp/artifact.tar.gz
    dest: /home/ubuntu/backend
    remote_src: yes

- name: Install dependencies
  npm:
    path: /home/ubuntu/backend

- name: Startup server
  shell: |
    cd /home/ubuntu/backend
    pm2 stop default
    pm2 start npm -- start
